#!/bin/sh

PREREQS="plymouth"

prereqs() { echo "$PREREQS"; }

case "$1" in
  prereqs) prereqs; exit 0 ;;
esac

. /usr/share/initramfs-tools/hook-functions

PLUGIN_DIR=/usr/lib/aarch64-linux-gnu/plymouth
THEME_DIR=/usr/share/plymouth/themes/writerdeck

if [ -d "${THEME_DIR}" ]; then
  mkdir -p "${DESTDIR}${THEME_DIR}"
  cp -a "${THEME_DIR}/." "${DESTDIR}${THEME_DIR}/"
fi

for plugin in script.so label-pango.so label-freetype.so; do
  if [ -f "${PLUGIN_DIR}/${plugin}" ]; then
    copy_exec "${PLUGIN_DIR}/${plugin}"
  fi
done
